"""devices_active_field

Revision ID: 0bdc06ca61d8
Revises: 5ca80d8c620f
Create Date: 2026-07-10 01:55:01.293169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdc06ca61d8'
down_revision: Union[str, None] = '5ca80d8c620f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'active')
    # ### end Alembic commands ###
