"""add payroll_concepts and branch catalog fields

Revision ID: 1cb211630d80
Revises: 7933b4efe343
Create Date: 2026-07-07 23:19:17.576693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb211630d80'
down_revision: Union[str, None] = '7933b4efe343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calculation_method', sa.String(length=20), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('branches', sa.Column('accounting_account', sa.String(length=50), nullable=True))
    op.add_column('branches', sa.Column('supervisor_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'branches', 'users', ['supervisor_user_id'], ['id'])
    # ### end Alembic commands ###

    # RLS multi-tenant (patrón estándar del proyecto, ver CLAUDE.md)
    op.execute("ALTER TABLE payroll_concepts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE payroll_concepts FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON payroll_concepts
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'supervisor_user_id')
    op.drop_column('branches', 'accounting_account')
    op.drop_table('payroll_concepts')
    # ### end Alembic commands ###
