"""payroll hours config

Revision ID: 35d554f0f7f6
Revises: 4658e9024305
Create Date: 2026-07-10 05:33:57.970789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d554f0f7f6'
down_revision: Union[str, None] = '4658e9024305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_hours_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pay_frequency', sa.String(length=20), nullable=False),
    sa.Column('standard_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pay_frequency', name='uq_payroll_hours_config_tenant_freq')
    )
    # ### end Alembic commands ###

    # RLS multi-tenant (patrón estándar del proyecto, ver CLAUDE.md)
    op.execute("ALTER TABLE payroll_hours_configs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE payroll_hours_configs FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON payroll_hours_configs
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_hours_configs')
    # ### end Alembic commands ###
