"""contract pay_frequency

Revision ID: 4658e9024305
Revises: c86a6d086bca
Create Date: 2026-07-10 05:02:40.767919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4658e9024305'
down_revision: Union[str, None] = 'c86a6d086bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('pay_frequency', sa.String(length=20), server_default=sa.text("'mensual'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'pay_frequency')
    # ### end Alembic commands ###
