"""consent record employee id nullable user id

Revision ID: 49f256cdc66e
Revises: c39608bf9525
Create Date: 2026-07-08 02:06:16.288789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f256cdc66e'
down_revision: Union[str, None] = 'c39608bf9525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_records', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.alter_column('consent_records', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'consent_records', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consent_records', type_='foreignkey')
    op.alter_column('consent_records', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('consent_records', 'employee_id')
    # ### end Alembic commands ###
