"""shift_templates_active_field

Revision ID: 4b32b8dc9096
Revises: 0bdc06ca61d8
Create Date: 2026-07-10 02:21:47.303909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b32b8dc9096'
down_revision: Union[str, None] = '0bdc06ca61d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_templates', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_templates', 'active')
    # ### end Alembic commands ###
