"""payroll concept employer value

Revision ID: 69000e3acf91
Revises: c2744305b486
Create Date: 2026-07-10 06:46:55.345483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69000e3acf91'
down_revision: Union[str, None] = 'c2744305b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_concepts', sa.Column('employer_value', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_concepts', 'employer_value')
    # ### end Alembic commands ###
