"""add feature flags

Revision ID: 9d3b79054ab6
Revises: 0371085d39e5
Create Date: 2026-07-08 02:20:18.252455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3b79054ab6'
down_revision: Union[str, None] = '0371085d39e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tenant_feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('feature_flag_code', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['feature_flag_code'], ['feature_flags.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # RLS multi-tenant SOLO en tenant_feature_flags — feature_flags es catálogo
    # público de la plataforma (igual que tenants), no lleva RLS.
    op.execute("ALTER TABLE tenant_feature_flags ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenant_feature_flags FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON tenant_feature_flags
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)

    # Seed real del catálogo — refleja los módulos ya construidos y verificados.
    # category='core' se habilita por default para todo tenant sin fila de override
    # (ver core/feature_flags.py: is_feature_enabled). 'addon' se habilita por default.
    feature_flags_table = sa.table(
        "feature_flags",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("category", sa.String),
    )
    op.bulk_insert(feature_flags_table, [
        {"code": "rbac_branches", "name": "Sucursales y roles",
         "description": "Gestión de sucursales, roles y permisos (mód. 2)", "category": "core"},
        {"code": "legal_compliance", "name": "Cumplimiento legal",
         "description": "Consentimiento biométrico y auditoría, Ley 8968 (mód. 4)", "category": "core"},
        {"code": "payroll_catalogs", "name": "Catálogos de nómina",
         "description": "Conceptos de ingreso/deducción, cuentas contables (mód. 6)", "category": "core"},
        {"code": "employee_onboarding", "name": "Personal y onboarding",
         "description": "Ficha de empleado y contratos (mód. 9)", "category": "core"},
        {"code": "device_management", "name": "Gestión de dispositivos",
         "description": "Inventario de relojes marcadores biométricos (mód. 8)", "category": "addon"},
        {"code": "biometric_enrollment", "name": "Enrolamiento biométrico",
         "description": "Captura y gestión de biometría de empleados (mód. 10)", "category": "addon"},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
