"""mod14_time_exceptions

Revision ID: a3a546ef6b0d
Revises: a8b55b0a3c73
Create Date: 2026-07-08 03:49:54.523679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a546ef6b0d'
down_revision: Union[str, None] = 'a8b55b0a3c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=True),
    sa.Column('trust_flag_id', sa.UUID(), nullable=True),
    sa.Column('exception_type', sa.String(length=30), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trust_flag_id'], ['trust_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TABLE time_exceptions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE time_exceptions FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON time_exceptions
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON time_exceptions")
    op.drop_table('time_exceptions')
    # ### end Alembic commands ###
