"""add trust_flags

Revision ID: a8b55b0a3c73
Revises: 812d12b1f8bd
Create Date: 2026-07-08 02:54:54.362130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b55b0a3c73'
down_revision: Union[str, None] = '812d12b1f8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: se removió acá un op.drop_constraint('uq_attendance_device_employee_recorded_at', ...)
    # que autogenerate propuso por error — ese constraint es real (protege la dedup de
    # marcaciones, sección 4) y ahora está declarado en __table_args__ del modelo para
    # que autogenerate no lo vuelva a marcar como huérfano.
    # ### end Alembic commands ###

    # RLS multi-tenant (patrón estándar del proyecto, ver CLAUDE.md)
    op.execute("ALTER TABLE trust_flags ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE trust_flags FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON trust_flags
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_flags')
    # ### end Alembic commands ###
