"""orquestacion_payroll_run

Revision ID: b01b17e5fbc8
Revises: a372cffde918
Create Date: 2026-07-11 07:09:11.327307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01b17e5fbc8'
down_revision: Union[str, None] = 'a372cffde918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_anomaly_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('net_deviation_pct_threshold', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_hours_multiplier_threshold', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('bank_account_change_window_days', sa.Integer(), nullable=False),
    sa.Column('branch_net_deviation_pct_threshold', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_payroll_anomaly_config_tenant')
    )
    op.create_table('payroll_snapshot_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ccss_deduction', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('renta_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('renta_is_refund', sa.Boolean(), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_period_id', 'employee_id', name='uq_payroll_snapshot_period_employee')
    )
    op.add_column('trust_flags', sa.Column('payroll_period_id', sa.UUID(), nullable=True))
    op.add_column('trust_flags', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.alter_column('trust_flags', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'trust_flags', 'payroll_periods', ['payroll_period_id'], ['id'])
    op.create_foreign_key(None, 'trust_flags', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


    for _table in ("payroll_anomaly_configs", "payroll_snapshot_lines"):
        op.execute(f"ALTER TABLE {_table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_table} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {_table}
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
            WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trust_flags', type_='foreignkey')
    op.drop_constraint(None, 'trust_flags', type_='foreignkey')
    op.alter_column('trust_flags', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('trust_flags', 'branch_id')
    op.drop_column('trust_flags', 'payroll_period_id')
    op.drop_table('payroll_snapshot_lines')
    op.drop_table('payroll_anomaly_configs')
    # ### end Alembic commands ###
