"""cesantia

Revision ID: b36b15cd58ab
Revises: b8497a9c3495
Create Date: 2026-07-11 04:03:10.724556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36b15cd58ab'
down_revision: Union[str, None] = 'b8497a9c3495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cesantia_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('max_years_cap', sa.Integer(), nullable=False),
    sa.Column('fraction_round_months', sa.Integer(), nullable=False),
    sa.Column('days_3to6_months', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('days_6to12_months', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('daily_divisor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('months_for_average', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_cesantia_config_tenant')
    )
    op.create_table('cesantia_scale_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year_number', name='uq_cesantia_scale_tenant_year')
    )
    op.create_table('terminations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=False),
    sa.Column('con_responsabilidad_patronal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', name='uq_termination_tenant_employee')
    )
    # ### end Alembic commands ###

    for _table in ("cesantia_configs", "cesantia_scale_rows", "terminations"):
        op.execute(f"ALTER TABLE {_table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_table} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {_table}
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
            WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminations')
    op.drop_table('cesantia_scale_rows')
    op.drop_table('cesantia_configs')
    # ### end Alembic commands ###
