"""aguinaldo_config

Revision ID: b8497a9c3495
Revises: 157d4b845e8d
Create Date: 2026-07-10 21:37:37.067466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8497a9c3495'
down_revision: Union[str, None] = '157d4b845e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aguinaldo_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start_month', sa.Integer(), nullable=False),
    sa.Column('period_start_day', sa.Integer(), nullable=False),
    sa.Column('period_end_month', sa.Integer(), nullable=False),
    sa.Column('period_end_day', sa.Integer(), nullable=False),
    sa.Column('divisor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_aguinaldo_config_tenant')
    )
    # ### end Alembic commands ###
    # RLS multi-tenant (patron estandar del proyecto, ver CLAUDE.md)
    op.execute("ALTER TABLE aguinaldo_configs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE aguinaldo_configs FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON aguinaldo_configs
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aguinaldo_configs')
    # ### end Alembic commands ###
