"""add slug to tenants

Revision ID: ba825cb61161
Revises: 0ea53c4adb31
Create Date: 2026-07-07 21:46:57.611156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba825cb61161'
down_revision: Union[str, None] = '0ea53c4adb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'tenants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###
